// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleSandrajService1.proto

package grpc.ca.sandraLibrary;

public interface ControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:samplesandrajservice1.ControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
