// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleSandrajService1.proto

package grpc.ca.sandraLibrary;

public interface ControlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:samplesandrajservice1.ControlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Action taken: "Cooling", "Heating", or "Maintaining"
   * </pre>
   *
   * <code>string action = 1;</code>
   */
  java.lang.String getAction();
  /**
   * <pre>
   * Action taken: "Cooling", "Heating", or "Maintaining"
   * </pre>
   *
   * <code>string action = 1;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();
}
