// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleSandrajService1.proto

package grpc.ca.sandraLibrary;

public final class SmartLibrarySandraImpl {
  private SmartLibrarySandraImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_samplesandrajservice1_ControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_samplesandrajservice1_ControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_samplesandrajservice1_ControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_samplesandrajservice1_ControlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033sampleSandrajService1.proto\022\025samplesan" +
      "drajservice1\"%\n\016ControlRequest\022\023\n\013temper" +
      "ature\030\001 \001(\005\"!\n\017ControlResponse\022\016\n\006action" +
      "\030\001 \001(\t2|\n\017AirConditioning\022i\n\022controlTemp" +
      "erature\022%.samplesandrajservice1.ControlR" +
      "equest\032&.samplesandrajservice1.ControlRe" +
      "sponse\"\000(\0010\001B1\n\025grpc.ca.sandraLibraryB\026S" +
      "martLibrarySandraImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_samplesandrajservice1_ControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_samplesandrajservice1_ControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_samplesandrajservice1_ControlRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_samplesandrajservice1_ControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_samplesandrajservice1_ControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_samplesandrajservice1_ControlResponse_descriptor,
        new java.lang.String[] { "Action", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
